test: &default

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jeremyby_api1.gmail.com
  password: DCDCEG2EUV387MVY
  signature: A0vRMvRTFWJMDFGr.4rGunwMOEb1AGq9myGZf1BSPao7oT1RaooJx9G7
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
