development: &default

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: upcommit-facilitator_api1.gmail.com
  password: 1405669912
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31Ajbp1BYKjmMBzu2Bb8bJ9UbtTEtQ
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: upcommit-facilitator@gmail.com


test:
  <<: *default
 
production:
  <<: *default
  
  app_id: APP-41A84619BU816430J
  
  username: jeremyby_api1.gmail.com
  password: DCDCEG2EUV387MVY
  signature: A0vRMvRTFWJMDFGr.4rGunwMOEb1AGq9myGZf1BSPao7oT1RaooJx9G7
   
  mode: live
