development: &default
  api_key: ylIYuefEqPjcaNrcEnfx7D0ZV
  api_secret: jrtwhrxuaT6Oua7cHrEl4ULhfE0naHp870SjHg2nMpIiH0Vvee
  access_token: 2650231424-xOUrj4ejqcHGz5VQ5qy5pqSEgJEOYbbzqY58vfL
  access_secret: M92RcIM1cAQ6ZIUtMHJN7bCttsS9zRiStO6oJ2ztHDNdR
test:
  <<: *default
  
production:
  api_key: n6ZsUUg7EXXq2ikFuRam484do
  api_secret: sKoKm30IfHbfCy9ljDIOhv0JLGFFB15q4em00Rfsla6liW0ldS
  access_token: 2650231424-AieylEIqubIsY2hghrFXbO7F6LHAZ2TFaK94wMe
  access_secret: zWbGSEzkRAlLnHOzLLwZHKDfm5Z6yAc29dOCq2UQCHRNc